/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_sistema_facturación;

import Controlador.UsuarioDAO;
import Modelo.NuevoUsuario;
import Modelo.ValidarDatos;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import static proyecto_sistema_facturación.Clientes.tablaClientes;
import static proyecto_sistema_facturación.Usuarios.tablaAdministrarUsuarios;

/**
 *
 * @author tmx
 */
public class EditarUsuario extends javax.swing.JFrame {

    String nombre;
    String usuario;
    String correo;
    String contraseña;
    String fecha;
    Conexion_BD.Conexion c = new Conexion_BD.Conexion();
    ValidarDatos validarDatos = new ValidarDatos();
    
    public EditarUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
       
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAgregarUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEditarNombreUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEditarUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEditarCorreoUsuario = new javax.swing.JTextField();
        pGuardarCambios = new javax.swing.JPanel();
        jGuardarCambios = new javax.swing.JLabel();
        pCancelar = new javax.swing.JPanel();
        jCancelar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEditarContraseñaUsuario = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtEditarConfirmarContraseña = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtIdEditarUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pAgregarUsuario.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nombre completo");

        txtEditarNombreUsuario.setText(" ");
        txtEditarNombreUsuario.setBorder(null);
        txtEditarNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEditarNombreUsuarioKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombre de usuario");

        txtEditarUsuario.setBorder(null);
        txtEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditarUsuarioActionPerformed(evt);
            }
        });
        txtEditarUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEditarUsuarioKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Correo electónico");

        txtEditarCorreoUsuario.setBorder(null);

        pGuardarCambios.setBackground(new java.awt.Color(204, 204, 255));
        pGuardarCambios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pGuardarCambios.setForeground(new java.awt.Color(255, 255, 255));
        pGuardarCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pGuardarCambiosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pGuardarCambiosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pGuardarCambiosMousePressed(evt);
            }
        });

        jGuardarCambios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jGuardarCambios.setText("Guardar cambios");

        javax.swing.GroupLayout pGuardarCambiosLayout = new javax.swing.GroupLayout(pGuardarCambios);
        pGuardarCambios.setLayout(pGuardarCambiosLayout);
        pGuardarCambiosLayout.setHorizontalGroup(
            pGuardarCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGuardarCambiosLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jGuardarCambios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pGuardarCambiosLayout.setVerticalGroup(
            pGuardarCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jGuardarCambios)
        );

        pCancelar.setBackground(new java.awt.Color(204, 204, 255));
        pCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pCancelarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pCancelarMousePressed(evt);
            }
        });

        jCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCancelar.setText("Cancelar");

        javax.swing.GroupLayout pCancelarLayout = new javax.swing.GroupLayout(pCancelar);
        pCancelar.setLayout(pCancelarLayout);
        pCancelarLayout.setHorizontalGroup(
            pCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCancelarLayout.createSequentialGroup()
                .addComponent(jCancelar)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        pCancelarLayout.setVerticalGroup(
            pCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCancelar, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Contraseña");

        txtEditarContraseñaUsuario.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Confirmar contraseña");

        txtEditarConfirmarContraseña.setBorder(null);
        txtEditarConfirmarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditarConfirmarContraseñaActionPerformed(evt);
            }
        });
        txtEditarConfirmarContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEditarConfirmarContraseñaKeyReleased(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Editar usuario");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        txtIdEditarUsuario.setEditable(false);
        txtIdEditarUsuario.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pAgregarUsuarioLayout = new javax.swing.GroupLayout(pAgregarUsuario);
        pAgregarUsuario.setLayout(pAgregarUsuarioLayout);
        pAgregarUsuarioLayout.setHorizontalGroup(
            pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pAgregarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addGroup(pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEditarContraseñaUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEditarCorreoUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEditarUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEditarNombreUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addComponent(txtEditarConfirmarContraseña, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(pAgregarUsuarioLayout.createSequentialGroup()
                        .addComponent(pGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAgregarUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIdEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pAgregarUsuarioLayout.setVerticalGroup(
            pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAgregarUsuarioLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditarNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditarCorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditarContraseñaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditarConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pAgregarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEditarNombreUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditarNombreUsuarioKeyReleased
        validarDatos.validarSoloLetras(txtEditarNombreUsuario);
    }//GEN-LAST:event_txtEditarNombreUsuarioKeyReleased

    private void txtEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditarUsuarioActionPerformed

    private void txtEditarUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditarUsuarioKeyReleased
        validarDatos.validarSoloLetras(txtEditarUsuario);
    }//GEN-LAST:event_txtEditarUsuarioKeyReleased

    private void pGuardarCambiosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pGuardarCambiosMouseEntered
        jGuardarCambios.setForeground(Color.WHITE);
        pGuardarCambios.setBackground(new Color(51,0,255));
        pGuardarCambios.setBorder(new LineBorder(new Color(51,0,255),1,true));
    }//GEN-LAST:event_pGuardarCambiosMouseEntered

    private void pGuardarCambiosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pGuardarCambiosMouseExited
        jGuardarCambios.setForeground(Color.BLACK);
        pGuardarCambios.setBackground(new Color(204,204,255));
        pGuardarCambios.setBorder(new LineBorder(new Color(204,204,255),1,true));
    }//GEN-LAST:event_pGuardarCambiosMouseExited

    private void pGuardarCambiosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pGuardarCambiosMousePressed
        String pass = new String(txtEditarContraseñaUsuario.getPassword());
        String passConf = new String(txtEditarConfirmarContraseña.getPassword());

        nombre = txtEditarNombreUsuario.getText();
        usuario = txtEditarUsuario.getText();
        correo = txtEditarCorreoUsuario.getText();
        contraseña = txtEditarConfirmarContraseña.getText().toString();
        fecha = "";

        if(!nombre.isEmpty() && !usuario.isEmpty() && !correo.isEmpty() && !contraseña.isEmpty()){
            if(pass.equals(passConf)){

                Pattern pattern = Pattern.compile(fecha)
                .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
                Matcher mather = pattern.matcher(correo);

                if(mather.find()==true){
                    NuevoUsuario editarUsuario = new NuevoUsuario(nombre, usuario, correo, contraseña, fecha);
                    new UsuarioDAO().ActualizarUsuario(editarUsuario, txtIdEditarUsuario.getText());
                    this.setVisible(false);
                    DefaultTableModel modelo = c.usuarios("SELECT * FROM RegistroDeUsuarios"); 
                    tablaAdministrarUsuarios.setModel(modelo); 

                    

                }else{
                    JOptionPane.showMessageDialog(null, "Correo ingresado no válido", "Error al registrar", JOptionPane.ERROR_MESSAGE);
                }

            }else{
                JOptionPane.showMessageDialog(null, "La contraseña no coincide", "Error", JOptionPane.ERROR_MESSAGE);

            }
        }else{
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos", "Error al registrar", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_pGuardarCambiosMousePressed

    private void pCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCancelarMouseEntered
        jCancelar.setForeground(Color.WHITE);
        pCancelar.setBackground(new Color(51,0,255));
        pCancelar.setBorder(new LineBorder(new Color(51,0,255),1,true));
    }//GEN-LAST:event_pCancelarMouseEntered

    private void pCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCancelarMouseExited
        jCancelar.setForeground(Color.BLACK);
        pCancelar.setBackground(new Color(204,204,255));
        pCancelar.setBorder(new LineBorder(new Color(204,204,255),1,true));
    }//GEN-LAST:event_pCancelarMouseExited

    private void pCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCancelarMousePressed

        this.setVisible(false);

    }//GEN-LAST:event_pCancelarMousePressed

    private void txtEditarConfirmarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditarConfirmarContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditarConfirmarContraseñaActionPerformed

    private void txtEditarConfirmarContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditarConfirmarContraseñaKeyReleased

    }//GEN-LAST:event_txtEditarConfirmarContraseñaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCancelar;
    private javax.swing.JLabel jGuardarCambios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pAgregarUsuario;
    private javax.swing.JPanel pCancelar;
    private javax.swing.JPanel pGuardarCambios;
    public static javax.swing.JPasswordField txtEditarConfirmarContraseña;
    public static javax.swing.JPasswordField txtEditarContraseñaUsuario;
    public static javax.swing.JTextField txtEditarCorreoUsuario;
    public static javax.swing.JTextField txtEditarNombreUsuario;
    public static javax.swing.JTextField txtEditarUsuario;
    public static javax.swing.JTextField txtIdEditarUsuario;
    // End of variables declaration//GEN-END:variables
}
