/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_sistema_facturación;

import Controlador.ClienteDAO;
import Modelo.Cliente;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import static proyecto_sistema_facturación.Clientes.tablaClientes;

/**
 *
 * @author tmx
 */
public class EliminarRegistro extends javax.swing.JFrame {

    Conexion_BD.Conexion c = new Conexion_BD.Conexion();
    
    public EliminarRegistro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pEliminar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pSiEliminar = new javax.swing.JPanel();
        jSiEliminar = new javax.swing.JLabel();
        pNoEliminar = new javax.swing.JPanel();
        jNoEliminar = new javax.swing.JLabel();
        txtxRegistro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setText("¿Esta seguro de eliminar");

        pSiEliminar.setBackground(new java.awt.Color(204, 204, 255));
        pSiEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pSiEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pSiEliminarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pSiEliminarMousePressed(evt);
            }
        });

        jSiEliminar.setText("Si");

        javax.swing.GroupLayout pSiEliminarLayout = new javax.swing.GroupLayout(pSiEliminar);
        pSiEliminar.setLayout(pSiEliminarLayout);
        pSiEliminarLayout.setHorizontalGroup(
            pSiEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSiEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSiEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pSiEliminarLayout.setVerticalGroup(
            pSiEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSiEliminar)
        );

        pNoEliminar.setBackground(new java.awt.Color(204, 204, 255));
        pNoEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pNoEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pNoEliminarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pNoEliminarMousePressed(evt);
            }
        });

        jNoEliminar.setText("No");

        javax.swing.GroupLayout pNoEliminarLayout = new javax.swing.GroupLayout(pNoEliminar);
        pNoEliminar.setLayout(pNoEliminarLayout);
        pNoEliminarLayout.setHorizontalGroup(
            pNoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNoEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jNoEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pNoEliminarLayout.setVerticalGroup(
            pNoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jNoEliminar)
        );

        txtxRegistro.setEditable(false);
        txtxRegistro.setBackground(new java.awt.Color(215, 215, 215));
        txtxRegistro.setBorder(null);

        jLabel4.setText("el registro");

        jLabel5.setText("?");

        javax.swing.GroupLayout pEliminarLayout = new javax.swing.GroupLayout(pEliminar);
        pEliminar.setLayout(pEliminarLayout);
        pEliminarLayout.setHorizontalGroup(
            pEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEliminarLayout.createSequentialGroup()
                .addGroup(pEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pEliminarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(pSiEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pNoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pEliminarLayout.createSequentialGroup()
                                .addComponent(txtxRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pEliminarLayout.setVerticalGroup(
            pEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEliminarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtxRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(pEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pSiEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pNoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pSiEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSiEliminarMousePressed
        
        String sql3 = "DELETE FROM Clientes WHERE id_Cliente="+txtxRegistro.getText()+"";
        
        Cliente eliminarCliente = new Cliente();
        new ClienteDAO().EliminarCliente(eliminarCliente, sql3);
        
        DefaultTableModel modelo = c.clientes("SELECT * FROM Clientes"); 
                    tablaClientes.setModel(modelo); 
                    this.setVisible(false);
    }//GEN-LAST:event_pSiEliminarMousePressed

    private void pNoEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pNoEliminarMousePressed
        this.setVisible(false);
    }//GEN-LAST:event_pNoEliminarMousePressed

    private void pSiEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSiEliminarMouseEntered
        jSiEliminar.setForeground(Color.WHITE);
        pSiEliminar.setBackground(new Color(51,0,255));
        pSiEliminar.setBorder(new LineBorder(new Color(51,0,255),1,true));
    }//GEN-LAST:event_pSiEliminarMouseEntered

    private void pSiEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSiEliminarMouseExited
        jSiEliminar.setForeground(Color.BLACK);
        pSiEliminar.setBackground(new Color(204,204,255));
        pSiEliminar.setBorder(new LineBorder(new Color(204,204,255),1,true));
    }//GEN-LAST:event_pSiEliminarMouseExited

    private void pNoEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pNoEliminarMouseEntered
        jNoEliminar.setForeground(Color.WHITE);
        pNoEliminar.setBackground(new Color(51,0,255));
        pNoEliminar.setBorder(new LineBorder(new Color(51,0,255),1,true));
    }//GEN-LAST:event_pNoEliminarMouseEntered

    private void pNoEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pNoEliminarMouseExited
        jNoEliminar.setForeground(Color.BLACK);
        pNoEliminar.setBackground(new Color(204,204,255));
        pNoEliminar.setBorder(new LineBorder(new Color(204,204,255),1,true));
    }//GEN-LAST:event_pNoEliminarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jNoEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jSiEliminar;
    private javax.swing.JPanel pEliminar;
    private javax.swing.JPanel pNoEliminar;
    private javax.swing.JPanel pSiEliminar;
    public static javax.swing.JTextField txtxRegistro;
    // End of variables declaration//GEN-END:variables
}
